apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: {{ index .Values "config-server" "replicaCount" }}
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: "{{ .Values.global.imageRepository }}/config-server:{{ .Values.global.imageTag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"