apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: {{ index .Values "eureka-server" "replicaCount" }}
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: "{{ .Values.global.imageRepository }}/eureka-server:{{ .Values.global.imageTag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"