apiVersion: apps/v1
kind: Deployment
metadata:
  name: order
spec:
  replicas: {{ .Values.order.replicaCount }}
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
        - name: order
          image: "{{ .Values.global.imageRepository }}/order:{{ .Values.global.imageTag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"