apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: {{ .Values.payment.replicaCount }}
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: "{{ .Values.global.imageRepository }}/payment:{{ .Values.global.imageTag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"