apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  replicas: {{ .Values.products.replicaCount }}
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
        - name: products
          image: "{{ .Values.global.imageRepository }}/products:{{ .Values.global.imageTag }}"
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"