name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Construire l'image (adapte pour chaque microservice)
      - name: Build users image
        run: docker build -t users:latest ./services/users

      # Installer Kind (Kubernetes in Docker)
      - name: Set up KinD
        uses: engineerd/setup-kind@v0.5.0

      # Charger l'image dans Kind
      - name: Load Docker image into Kind
        run: kind load docker-image users:latest

      # Installer Helm
      - name: Install Helm
        uses: azure/setup-helm@v4

      # Déployer avec Helm
      - name: Deploy Users service
        run: helm upgrade --install users ./charts/users

      # Vérifier le déploiement
      - name: Check deployments
        run: kubectl get pods -A
